### Pacote numpy
Numpy é um o pacote que contém diversas funções matemáticas e de manipulação de matrizes multidimensionais. Para os exemplos utilizados nesse material, ilustramos algumas funções básicas que precisarão ser utilizadas.

### Instalação

Existem diversas formas de instalar o pacote numpy.
**Anaconda:**

```conda install -c anaconda numpy.```

**Pip:**

```pip install numpy```

```pip install -U numpy```
o

```python -m pip install numpy```

**apt-get**: 

```sudo apt-get install python-numpy ```

[**Link Instalação numpy**](https://scipy.org/install.html)
         

### Importação


In [1]:
import numpy as np

### Criação de matrizes
Podemos criar matrizes utilizando a função array(). Nela passamos como parâmetros os elementos que vão preencher a matriz no formato de lista <b>[1, 2, 3]</b> ou tupla <b>(1, 2, 3)</b>. Cada posição do parâmetro da função representa uma linha distinta da matriz, que pode conter elementos heterogêneos, ou seja, as matrizes podem conter diferentes tipos de dados. 

In [2]:
matriz_a = np.array([2, 3, 4])
print(" Matriz A: \n", matriz_a)

matriz_b = np.array([1.2, 3.5, 5.1])
print(" Matriz B: \n", matriz_b)

matriz_c = np.array([(1.5, 2, 3), (4, 'a', 6)])
print(" Matriz C: \n", matriz_c)


 Matriz A: 
 [2 3 4]
 Matriz B: 
 [1.2 3.5 5.1]
 Matriz C: 
 [['1.5' '2' '3']
 ['4' 'a' '6']]


### Funções

### arange() e reshape()
Podemos criar matrizes e preenchê-las com números dentro de um intervalo utilizando **arange()** e definir as dimensões dessa matriz com o **reshape()**:

In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5) # A matriz sera preenchida com valores de 0 a 14, esses valores serao distribuidos entra 3 linhas e 5 colunas

print(" Matriz: \n", a)
print(" \nNúmero de linhas e colunas: ", a.shape)
print(" \nNúmero de dimensões(axes):", a.ndim)
print(" \nTipo dos elementos: ", a.dtype.name)
print(" \nNúmero de elementos: ", a.size)
print(" \nTamanho em bytes: ", a.itemsize)

 Matriz: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
 
Número de linhas e colunas:  (3, 5)
 
Número de dimensões(axes): 2
 
Tipo dos elementos:  int64
 
Número de elementos:  15
 
Tamanho em bytes:  8


### zeros() e ones()
As funções da **zeros()** e **ones()** da biblioteca numpy geram matrizes de zeros ou uns respectivamente, há como definir o tipo dos elementos e as dimensões da matriz.

In [2]:
zeros = np.zeros( (3,4) )
print(zeros)

z_inteiros = np.zeros((4, 4), dtype=np.int16)
print(z_inteiros)

ones = np.ones( (2, 2))
print(ones)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1.]
 [1. 1.]]


Há como definir diversas formas de gerar intevalos de números para popular a tabela, ou até mesmo usar um gerador de números aleatórios.

In [5]:
 np.arange( 10, 30, 5 )
    

array([10, 15, 20, 25])

In [6]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Fonte: Fonte: https://numpy.org/devdocs/user/quickstart.html